### PR TITLE
Fixed bug in conversion of thermal location from lat/lon to meters. t…

### PR DESCRIPTION
**Pull request by philipoe**
…his caused thermals to be an ellipse instead of a circle, and also caused the thermal radius to be incorrect of course.

Note that the simple addition of the cosine of the latitude to the conversion calculation fixes the issue. The absolutely correct way would be to use cos (0.5*(lat1+lat2)) for the correction factor, but the respective variables for the plane and the thermal are not available in all functions, so we will take the simple route and just take the plane latitude in all cases.

### CODE REVIEW

**Comment by alexferrer** [comment]
Thanks for the patch!  In real life, thermals are hardly perfect circles (specially when closer to the terrain )  Most of the time thermals while climbing are deformed by wind, terrain, and interaction with other rising thermals. At some time it would be cool to purposely deform them to add to the realism of the game. 
Again, thanks for the patch !

**Comment by philipoe** [comment]
Hi Alex, agreed that thermals are nearly nevery perfectly circular in reality, but with the updated distance calculation we can now start integrating what ever model we want (currently I am using a Gaussian Distribution, see e.g. the paper at http://enu.kz/repository/2010/AIAA-2010-179.pdf . At least in academia, this seems to be the most widely accepted approach (it is really easy to implement, and the glider community seems to be OK with it, too).

**Comment by alexferrer** [comment]
Interesting paper.. I think he is missing one of the best tools we glider pilots have to locate thermals; The roll of the wing created by the differential of lift strength between your wing tips (on standard gliders ~ 15 meters).  Even on fast straight flight , the induced roll will immediately tell you if the thermal is to your left or right. (this behaviour is incorporated on function CalcThermal) 
Another important factor to realistically simulate a real thermal is the thermal strength variation associated with altitude. on the plugin, I do have a function ThermalBand, but at the moment is over simplistic and accounts only for the thermal strength reduction as you get closer to cloud base altitude. 

In any case, if you are interested on working on anything on the plugin and you need any "real flight" experience questions.. (are you a pilot?) I'll be glad to help you as best as I can.  ( I got *many* years of practice chasing thermals on gliders & paragliders )

**Comment by philipoe** [comment]
Hi, interesting point with the induced wing roll. And actually, I am working on something exactly like that, i.e. I saw that your plugin models this induced wing roll effect, and I am working on an extension of the above paper that will also use this experienced roll to estimate the thermal position.

I am not a pilot, but we do a lot of (autopiloted) RC model flying and thermal hunting. In that respect, it is already good to hear from you that the induced roll effect is a good source of information (at least in large gliders).

**Pull request merged**
